### ISSUE TITLE
Unable to run jim

### ISSUE THREAD

**Issue by netrose** [p-fruck/jim#31]
Trying to run without docker as specified using the commands I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jim@2.1.3~prestart: jim@2.1.3
6 info lifecycle jim@2.1.3~start: jim@2.1.3
7 verbose lifecycle jim@2.1.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle jim@2.1.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/jim-admin/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle jim@2.1.3~start: CWD: /tmp/jim-admin
10 silly lifecycle jim@2.1.3~start: Args: [ '-c', 'ts-node ./src/index.ts' ]
11 silly lifecycle jim@2.1.3~start: Returned: code: 1  signal: null
12 info lifecycle jim@2.1.3~start: Failed to exec start script
13 verbose stack Error: jim@2.1.3 start: `ts-node ./src/index.ts`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid jim@2.1.3
15 verbose cwd /tmp/jim-admin
16 verbose Linux 4.15.0-154-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error jim@2.1.3 start: `ts-node ./src/index.ts`
22 error Exit status 1
23 error Failed at the jim@2.1.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

and on the command line I get this:

```
npm run start

> jim@2.1.3 start /tmp/jim-admin
> ts-node ./src/index.ts

/tmp/jim-admin/src/jitsi-bot.ts:164
        if (!track?.formats?.length) {
                   ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Module.m._compile (/tmp/jim-admin/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.require.extensions.<computed> [as .ts] (/tmp/jim-admin/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/jim-admin/src/index.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jim@2.1.3 start: `ts-node ./src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jim@2.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-02T11_29_32_679Z-debug.log

```

**Comment by p-fruck** [comment]
Hi, thank you for trying out JIM! It appears to me that you are using an outdated nodejs version. JIM uses [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), which is a feature only supported in NodeJS >= 14. Updating your version of NodeJS therefore should resolve the issue.

ToDo:
- [ ] Add NodeJS version requirement to README.

**Comment by netrose** [comment]
Using node 16.8.0 now. There is a different issue now:

`# npm run start

> jim@2.1.3 start
> ts-node ./src/index.ts

Error: Failed to launch the browser process!
/tmp/jim-admin/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/tmp/jim-admin/node_modules/puppeteer/src/node/BrowserRunner.ts:226:9)
    at Interface.<anonymous> (/tmp/jim-admin/node_modules/puppeteer/src/node/BrowserRunner.ts:212:50)
    at Interface.emit (node:events:406:35)
    at Interface.emit (node:domain:475:12)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at Socket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Comment by netrose** [comment]
I also tried node 14.17.6 with the same result

**Comment by p-fruck** [comment]
Ok, we are one step further. The current error means that some library is missing on your system.

Puppeteer already provides you with a [troubleshooting](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) link where all necessary dependencies are listed for Debian/Ubuntu and CentOS/Fedora.

Please try to install those packages, which should resolve the issue.

In case it does not work (or you are using some different flavour of Linux, e.g. Arch),  you can also install the chromium-browser on you system, which should provide you with all necessary dependencies (the regular version, not something sandboxed like snap or flatpak).

**Comment by p-fruck** [comment]
The setup wiki now exists in a very early stage and can be seen [here](https://github.com/p-fruck/jim/wiki/Setup-\(NodeJS\)). It should contain all necessary information to setup JIM, tested on Debian 11 bullseye. I am now closing the issue, feel free to report back if the instructions are understandable and reopen the issue if new problems occur :wink:
